### ISSUE TITLE
bitget subscribes to the ORDER_UPDATE channel  for question

### ISSUE THREAD

**Issue by dongpuxiao** [crypto-chassis/ccapi#414] opened 2023-08-11 10:16 UTC
Hello, after testing, when the bitget market subscribes to the ORDER_UPDATE channel, if an order change event is triggered, the message will not be pushed and will be adjusted, but the gate and huobi do not have this problem. How to solve it?

**Comment by cryptochassis** [comment] 2023-08-17 19:37
Thanks a lot for reporting. We've found the root cause and have verified that we can successfully subscribe to bitget spot for ORDER_UPDATE. The fix is in https://github.com/crypto-chassis/ccapi/pull/417 which will be merged once it passed all tests.

**Comment by dongpuxiao** [comment] 2023-08-19 13:39
Hello, it seems that the subscription can return success for the first time, **but when the order is completed and the event is triggered**, the subscription order data will still not be actively pushed. Please confirm whether this problem exists, thank you

**Comment by cryptochassis** [comment] 2023-08-20 03:00
Please make sure that the symbol that you used does exist on the exchange. If it doesn't, you might observe that issue.

**Closed** 2023-09-12 17:53 UTC
