### ISSUE TITLE
Multiple private subscriptions

### ISSUE THREAD

**Issue by quazzuk** [crypto-chassis/ccapi#125] opened 2021-05-25 18:33 UTC
**Describe the bug**
Subscribing to both the `CCAPI_EM_ORDER_UPDATE` and `CCAPI_EM_PRIVATE_TRADE` channels as well as orderbook updates on FTX is resulting in the following message:

```Message [type = GENERIC_ERROR, recapType = UNKNOWN, time = 2021-05-25T18:07:55.277796000Z, timeReceived = 2021-05-25T18:07:55.277796000Z, elementList = [ Element [nameValueMap = {ERROR_MESSAGE=timer: The operation was aborted, category: websocketpp.transport}] ], correlationIdList = [  ]]```

**To Reproduce**
```
Subscription spotDepthSub("ftx", "BTC/USD", CCAPI_MARKET_DEPTH, "", "BTC");
Subscription perpDepthSub("ftx", "ETH/USD", CCAPI_MARKET_DEPTH, "", "ETH");
Subscription ordersSub("ftx"," ", CCAPI_EM_ORDER_UPDATE, "", "ORDERS");
Subscription fillsSub("ftx", "", CCAPI_EM_PRIVATE_TRADE, "", "FILLS");

session.subscribe({spotDepthSub, perpDepthSub, fillsSub, ordersSub});
```

**Expected behavior**
No error and receive events on both private fill and order channels plus book updates.

**Additional Context**
The strange thing is when I try to debug with a debugger it appears to work, not tracked down why this is the case perhaps build setting or XCode is using a different version of clang.

I've added a print statement to Service::connectionAddressToString to print the connection address. In the working example the connection address is different for the book, order and fills subscriptions. In the non-working case the address is always the same, which looks wrong. Any ideas what could be causing this?

**Comment by quazzuk** [comment] 2021-05-25 20:16
ok, the difference in behaviour seems to be down to the following line:

```TlsClient::connection_ptr con = this->serviceContextPtr->tlsClientPtr->get_connection(url, ec);```

in the working scenario for the same url (`wss://ftx.com/ws`) the returned connection ptr address is different in each case and for the other setup it's the same. 

Should the connection be reused for the same url? If yes, should there be multiple logon (as there is) for the private channel or should this be done once per authorised channel/connection pair?

**Comment by cryptochassis** [comment] 2021-05-31 16:00
@quazzuk I'm unable to reproduce the issue using macOS and clang. In Xcode, could you perform a "Clean" which clears old build cache, and perform a fresh build to see whether you can still observe the problem or not?

**Comment by cryptochassis** [comment] 2021-07-24 21:11
@quazzuk I'm going to close the issue for now. If you encounter it again, feel free to reopen it. Today I performed another round of tests around this issue, both in Debug mode and Release mode, and ran the program for extended period of time. The reported issue didn't show up and the program exited error-free.

**Closed by cryptochassis** 2021-07-24 21:11 UTC
