### ISSUE TITLE
Intermittent create order failures

### ISSUE THREAD

**Issue by quazzuk** [crypto-chassis/ccapi#121] opened 2021-05-18 07:18 UTC
**Describe the bug**
 Create order intermittently fails with the following:

```
2021-05-18T01:38:12.933153084Z ERROR - errorMessage = read: end of stream, category: beast.http
2021-05-18T01:38:12.933272015Z ERROR - correlationIdList = [ SPOT_BTC ]
Event [
  type = REQUEST_STATUS,
  messageList = [
    Message [
      type = REQUEST_FAILURE,
      recapType = UNKNOWN,
      time = 2021-05-18T01:38:12.933380067Z,
      timeReceived = 2021-05-18T01:38:12.933380067Z,
      elementList = [
        Element [
          nameValueMap = {
            ERROR_MESSAGE = read: end of stream, category: beast.http
          }
        ]
      ],
      correlationIdList = [ SPOT_BTC ]
    ]
  ]
]
2021-05-18T01:38:12.933618040Z ERROR - max retry exceeded
2021-05-18T01:38:12.933712752Z ERROR - errorMessage = max retry exceeded
2021-05-18T01:38:12.933810483Z ERROR - correlationIdList = [ SPOT_BTC]
Event [
  type = REQUEST_STATUS,
  messageList = [
    Message [
      type = REQUEST_FAILURE,
      recapType = UNKNOWN,
      time = 2021-05-18T01:38:12.933906665Z,
      timeReceived = 2021-05-18T01:38:12.933906665Z,
      elementList = [
        Element [
          nameValueMap = {
            ERROR_MESSAGE = max retry exceeded
          }
        ]
      ],
      correlationIdList = [ SPOT_BTC ]
    ]
  ]
]
```

**To Reproduce**
1. I just need to run my code for any reasonable period of time using the FTX services. I've checked the request payload and it all looks fine when printed. 

**Expected behavior**
Order submitted successfully.

**Additional context**
Based on a bit of googling it seems `read: end of stream, category: beast.http` means the connection was closed by the remote side. Perhaps there is something wrong with my request or the connection is stale?

At this point I'm just checking whether you've seen this issue before or have any suggestions for how to debug?

Thanks

**Comment by BroBan** [comment] 2021-05-18 07:25
@quazzuk We have seen the same behavior on FTX. You got the cause of the error right - it's FTX closing the open connection that the code is trying to reuse, but i haven't tried to figure out why this is happening or how to keep it open. But the workaround for it is to retry the request if if fails. You can achieve that by modifying the SessionOptions and set the httpMaxNumRetry to 1 instead of the default 0, we haven't had any problems since we changed it to 1. So in your main class you can do:
```
SessionOptions sessionOptions;
sessionOptions.httpMaxNumRetry = 1;
```

**Comment by quazzuk** [comment] 2021-05-18 07:27
Awesome, I'll try that. Thanks for the quick response!

**Comment by cryptochassis** [comment] 2021-05-20 05:14
Change in develop branch: https://github.com/crypto-chassis/ccapi/commit/33a8c62d8e650922121332d02b9dd26d9f3d8f5f

**Closed** 2021-05-27 04:02 UTC
